CXX=mcxx
EXTENSION=.exe
DUMMY_PROG=dummy
TRACER_PROG=tracer
CXXFLAGS=-O2 -std=c++11 -g
LDFLAGS=
DEFS=

$(DUMMY_PROG)$(EXTENSION): $(DUMMY_PROG).cpp
	$(CXX) $(CXXFLAGS) $(DUMMY_PROG).cpp -o $(DUMMY_PROG)$(EXTENSION) $(LDFLAGS) $(DEFS)

d: $(DUMMY_PROG)$(EXTENSION)

rd: d
	./$(DUMMY_PROG)$(EXTENSION)

$(TRACER_PROG)$(EXTENSION): $(DUMMY_PROG)$(EXTENSION) $(TRACER_PROG).cpp
	c++ $(CXXFLAGS) $(TRACER_PROG).cpp -o $(TRACER_PROG)$(EXTENSION) $(LDFLAGS) $(DEFS)

t: $(TRACER_PROG)$(EXTENSION)

rt: t
	./$(TRACER_PROG)$(EXTENSION) dummy.exe

clean:
	rm -rf *.o *$(EXTENSION) *.dSYM
